spring:
  application:
    name: redis-cache-practise

  datasource:
    url: jdbc:mysql://localhost:3306/redis-cache-practise
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  docker:
    compose:
      enabled: true
      file: src/main/resources/docker-compose.yml

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
